package com.meal.recommend_food.components;


import com.meal.recommend_food.services.FoodService;
import jakarta.annotation.PostConstruct;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

@Component
public class AddDataComponent {
    private final FoodService foodService;
    public AddDataComponent(FoodService foodService) {
        this.foodService = foodService;
    }
    public List<String> makeList (){
        return Arrays.asList("Cá Hú",
                "Thịt Heo Kho Trứng Cút",
                "Thịt Heo Nạc Chiên Sả",
                "Hồng Xiêm",
                "Bò Xào Hành" ,
                "Bánh Canh Tôm Thịt" ,
                "Gỏi Măng Tươi" ,
                "Canh Mướp Mồng Tơi" ,
                "Nước Dừa Tươi Non" ,
                "Canh Mồng Tơi Nấu Thịt Heo" ,
                "Bắp Cải Luộc" ,
                "Súp Lơ Cà Rốt Luộc" ,
                "Ổi" ,
                "Chuối Tiêu" ,
                "Bông Cải Cà Rốt Xào" ,
                "Lê" ,
                "Ếch Chiên Nước Mắm" ,
                "Giá Hẹ Xào" ,
                "Súp Lơ Xanh Xào" ,
                "Canh Rau Má" ,
                "Canh Cải Thảo Nấu Thịt Heo" ,
                "Súp Lơ Xanh Xào Cà Rốt" ,
                "Chả Mực Chiên" ,
                "Miến Trộn Chay" ,
                "Canh Rong Biển Nấu Thịt Bò" ,
                "Bánh Canh Cua" ,
                "Canh Đu Đủ" ,
                "Giá Hẹ Xào Thịt Gà" ,
                "Nấm Rơm Xào Đậu Hủ" ,
                "Bánh Bao Nhân Thịt" ,
                "Vịt Kho Gừng" ,
                "Chuối Già" ,
                "Canh Mướp Mồng Tơi Nấu Tôm" ,
                "Rau Củ Xào Thập Cẩm" ,
                "Canh Đu Đủ Xanh Nấu Tôm" ,
                "Canh Khổ Qua Nấm" ,
                "Canh Rau Ngót Thịt Heo" ,
                "Canh Bí Đao Nấu Thịt Heo" ,
                "Canh Bông Cải Nấm Rơm Thịt Heo" ,
                "Canh Bí Đao Nấu Tôm" ,
                "Quít" ,
                "Canh Rau Dền Cơm Nấu Thịt Heo" ,
                "Bánh Canh Giò Heo" ,
                "Canh Mồng Tơi Nấu Tôm" ,
                "Mực Xào Thập Cẩm" ,
                "Chôm Chôm Nhãn" ,
                "Mận" ,
                "Súp Lơ Xanh Cà Rốt Xào" ,
                "Cơm" ,
                "Giá Mướp Xào Tôm Khô" ,
                "Mướp Xào" ,
                "Nui Xào Chay" ,
                "Bánh Cuốn" ,
                "Bông Hẹ Xào Thịt Bò" ,
                "Khoai Lang" ,
                "Cần Tây Xào Gan Heo" ,
                "Nuvi Sữa Lắc Trái Cây" ,
                "Canh Kim Chi" ,
                "Súp Lơ Xanh Cà Rốt Xào Thịt Bò" ,
                "Chả Cua Hấp" ,
                "Đậu Hũ Kho Nấm Rơm" ,
                "Sườn Nấu Đậu" ,
                "Chả Chay Kho Tiêu" ,
                "Tôm Chiên Giòn" ,
                "Canh Bắp Cải Cà Rốt" ,
                "Khổ Qua (Mướp Đắng) Xào" ,
                "Cà Chua Dồn Thịt Chay" ,
                "Đậu Bắp Luộc" ,
                "Cà Bát Xào Thịt Heo" ,
                "Chả Cá Thu Chiên" ,
                "Đậu Hủ Chiên Sả" ,
                "Chôm Chôm Thái" ,
                "Đào" ,
                "Bắp Cải Xào Thịt Heo" ,
                "Đậu Hũ Dồn Thịt Sốt Cà" ,
                "Táo Tây" ,
                "Sữa Đậu Nành Bổ Sung Canxi Nuti" ,
                "Miến Trộn Rau Củ Chay" ,
                "Cải Thìa Xào Tỏi" ,
                "Cải Thìa Xào Nấm Hương" ,
                "Cá Ngừ Kho Thơm" ,
                "Cải Thìa Xào Thịt Heo" ,
                "Cá Lóc Kho Tộ" ,
                "Canh Khổ Qua Nấu Cá Thác Lác" ,
                "Nuvi Sữa Chua Uống Men Sống Chai 65ml" ,
                "Canh Bí Đỏ Nấu Thịt Heo" ,
                "Nấm Xào Sả Ớt" ,
                "Canh Cà Rốt Khoai Tây Nấu Thịt Bằm" ,
                "Vú Sữa" ,
                "Nutimilk Sữa Tươi 100 Điểm Ít Đường Hộp 180ml" ,
                "Cải Thìa Sốt Nấm Đông Cô" ,
                "Gà Kho Hành Gừng" ,
                "Mực Xào Chua Ngọt" ,
                "Cá Nục Chiên" ,
                "Chả Cá Thát Lát Chiên" ,
                "Trứng Chiên Nấm" ,
                "Thịt Heo Sốt Chua Ngọt" ,
                "Canh Cải Cúc Nấu Tôm" ,
                "Cá Chim Chiên" ,
                "Canh Cải Xanh" ,
                "Đậu Hủ Chiên Chấm Tương" ,
                "Cốt Lết Ram Mè" ,
                "Cá Chim Kho Ngót" ,
                "Đu Đủ Chín" ,
                "Canh Chua Rau Muống Nấu Tôm" ,
                "Đậu Hũ Kho Thịt" ,
                "Bò Hầm Tiêu Xanh" ,
                "Nuvi Sữa Lắc Trái Cây Hương Cam Cho Trẻ 1 Tuổi Trở Lên Hộp 110ml" ,
                "Canh Đu Đủ Xanh Nấu Thịt Heo" ,
                "Súp Lơ Xanh Luộc" ,
                "Canh Rong Biển Nấu Tôm" ,
                "Tôm Sốt Nấm" ,
                "Dưa Leo" ,
                "Canh Khoai Mỡ" ,
                "Đậu Hũ Thịt Bằm Sốt Cà Chua" ,
                "Bánh Mì Thịt Nướng" ,
                "Cánh Gà Chiên Giòn" ,
                "Canh Su Su Cà Rốt" ,
                "Giá Mướp Xào Thịt Heo" ,
                "Nấm Sốt Dầu Hào" ,
                "Khổ Qua (Mướp Đắng) Xào Trứng" ,
                "Mì Quảng" ,
                "Xíu Mại Kho Cà" ,
                "Xoài Chín" ,
                "Bắp Cải Xào" ,
                "Sườn Non Xào Chua Ngọt" ,
                "Canh Đu Đủ Xanh Nấu Sườn Heo" ,
                "Dưa Bở" ,
                "Canh Bầu Nấu Thịt Bằm" ,
                "Phi Lê Cá Basa Chiên" ,
                "Cà Ry Đậu Hũ Chay" ,
                "Thịt Heo Kho Củ Cải" ,
                "Tàu Hủ Ky Xào Rau Củ" ,
                "Đậu Cô Ve (Đậu Que) Xào Thịt Bò" ,
                "Bí Đao Đậu Bắp Luộc" ,
                "Cà Tím Xào Thịt Bằm" ,
                "Đậu Rồng Luộc" ,
                "Cá Diêu Hồng Kho Hành Gừng" ,
                "Canh Khoai Mỡ Nấu Thịt Heo" ,
                "Tôm Sốt Cà" ,
                "Canh Cải Cúc Nấu Thịt Heo" ,
                "Đậu Hủ Kho Rau Củ Chay" ,
                "Nước Cam Tươi" ,
                "Nho Ngọt" ,
                "Rau Muống Xào Thịt Bò" ,
                "Đậu Que Xào Cà Rốt" ,
                "Thịt Ba Rọi Kho Mắm Ruôc" ,
                "Chả Giò Chay" ,
                "Đậu Hũ Sốt Cà" ,
                "Canh Cải Xanh Nấu Cá Thác Lác" ,
                "Bò Lúc Lắc" ,
                "Thịt Heo Nạc Kho Tiêu" ,
                "Sườn Cốt Lếch Ram" ,
                "Bầu Xào Thịt Bằm" ,
                "Cam Vàng" ,
                "Canh Khổ Qua Nhồi Thịt" ,
                "Nước Ép Cà Rốt 100%" ,
                "Canh Củ Sen Nấu Nấm Mỡ" ,
                "Canh Cải Bó Xôi Thịt Bò" ,
                "Gà Rô Ti" ,
                "Canh Khoai Củ Thịt Bằm" ,
                "Nhãn" ,
                "Ngọn Su Su Xào Thịt Bò" ,
                "Canh Bầu Nấu Tôm" ,
                "Mì Căn Xào Sả" ,
                "Cải Ngọt Xào Tỏi" ,
                "Tôm Rim Thịt Ba Rọi" ,
                "Xíu Mại Nhồi Trứng Cút" ,
                "Bắp Nếp Luộc" ,
                "Su Su Cà Rốt Xào Tôm" ,
                "Đậu Cove Luộc" ,
                "Nutimilk Sữa Chua Có Đường Hộp 100g" ,
                "Canh Chua Cá Thát Lát" ,
                "Bún Mọc" ,
                "Mãng Cầu Ta" ,
                "Gà Hấp Lá Chanh" ,
                "Táo Ta" ,
                "Súp Tôm" ,
                "Bò Xào Dưa Chua" ,
                "Cá Bống Chiên Giòn" ,
                "Canh Cải Bó Xôi Thịt Heo" ,
                "Quả Thanh Long" ,
                "Mì Ý Sốt Bò Bằm" ,
                "Canh Rau Ngót" ,
                "Canh Bắp Cải Nấu Tôm" ,
                "Cá Cơm/ Cá Bống Kho Tiêu" ,
                "Mít Non Xào" ,
                "Sườn Nướng Chay" ,
                "Nấm Rơm Xào Lòng Gà" ,
                "Quýt Đường" ,
                "Salad Trộn Giấm" ,
                "Bún Bò Huế" ,
                "Canh Khoai Tây Cà Rốt Nấm Hương" ,
                "Canh Bầu" ,
                "Bún Riêu Chay" ,
                "Trứng Cuộn Tam Sắc" ,
                "Cá Hú Kho Tiêu" ,
                "Miến Sườn Heo" ,
                "Canh Măng Chua Cá Điêu Hồng" ,
                "Bưởi" ,
                "Bầu Đậu Bắp Luộc" ,
                "Dưa Leo Cà Chua Xà Lách" ,
                "Thịt Heo Nhồi Cà Chua" ,
                "Dưa Hấu" ,
                "Đậu Cove" ,
                "Nutimilk Sữa Tươi 100 Điểm Có Đường Hộp 110ml" ,
                "Cải Chua Xào Thịt Heo" ,
                "Măng Xào Đậu Hũ" ,
                "Canh Cải Cúc Đậu Hũ" ,
                "Măng Cụt" ,
                "Rau Muống Luộc" ,
                "Miến Thịt Gà Nấu Nấm" ,
                "Canh Đu Đủ Xanh" ,
                "Susu Xào" ,
                "Dưa Lưới" ,
                "Dưa Lê" ,
                "Khoai Mì Chấm Muối Mè" ,
                "Canh Cà Rốt Khoai Tây Thịt Bằm" ,
                "Su Su Xào Tỏi" ,
                "Bò Xào Hành Cần" ,
                "Canh Rau Ngót Nấu Thịt Bằm" ,
                "Canh Chua Nấm Kim Châm" ,
                "Susu Cà Rốt Xào Chay" ,
                "Mì Xào Chay" ,
                "Mực Nhồi Thịt Chiên" ,
                "Cá Trê Chiên Mắm Gừng" ,
                "Canh Cải Thảo" ,
                "Canh Bí Đỏ Đậu Phộng" ,
                "Canh Rau Đay Nấu Cua" ,
                "Củ Sắn",
                "Đậu Hủ Kho Dưa Cải",
                "Canh Súp Lơ Cà Rốt",
                "Canh Cà Chua Trứng Gà",
                "Cải Ngọt Luộc", "Canh Rau Dền");
    }

    @PostConstruct
    public void init(){
        List<String> data = makeList();
        foodService.addData(data);
        System.out.println("Đã thực hiện thành công !");
    }
}
