package com.meal.recommend_food.components;


import com.meal.recommend_food.services.FoodService;
import com.opencsv.CSVReader;
import jakarta.annotation.PostConstruct;
import org.example.Pair;
import org.example.RecommendModel;
import org.springframework.stereotype.Component;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

@Component
public class AddDataComponent {
    private final FoodService foodService;
    public static List<List<Integer>> dataNumber;
    public static Map<String, Integer> dataMapping;
    public static Map<Integer, String> reverseMapping;
    public static RecommendModel recommendModel;
    public static Map<Pair<Integer, Double>, Map<Integer, Map<Integer,Double>>> trainedPairwise;
    public AddDataComponent(FoodService foodService) {
        this.foodService = foodService;
    }
    public static List<String> readData(String nameDataSet){
        List<String> data = new ArrayList<>();
        List<List<String>> records = new ArrayList<>();
        try(CSVReader csvReader = new CSVReader(new FileReader(nameDataSet));){
            String[] nextRecord = null;
            while ((nextRecord = csvReader.readNext()) != null){
                records.add(Arrays.asList(nextRecord));
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        for(int i = 1; i < records.size(); i++){
            data.add(records.get(i).get(1));
        }
        return data;
    }
    public void prepareData() throws InterruptedException {
        List<String> data = readData("C:\\Users\\ADMIN\\Desktop\\recommend-food\\recommend-food\\src\\main\\java\\com\\meal\\recommend_food\\dataset.csv");
        if(!data.isEmpty()){
            dataMapping = prepareData(data);
            reverseDataMapping(dataMapping);
            dataNumber = changeDataTrainToNumber(data, dataMapping);
            System.out.println("Dữ liệu đã chuyển đổi thành công");
            recommendModel = new RecommendModel();
            trainedPairwise = recommendModel.trainPairwise(dataNumber);
            System.out.println(trainedPairwise.size());
            System.out.println("Train pairwise thành công");
        }
    }
    public Map<String, Integer> prepareData(List<String> data){
        int i = 1;
        Map<String, Integer> listDataToMapping = new HashMap<>();
        for (String s : data){
            List<String> split = Arrays.stream(s.split(", ")).map(String::valueOf).toList();
            for (String s1 : split){
                if (!listDataToMapping.containsKey(s1)){
                    listDataToMapping.put(s1, i);
                    i++;
                }
            }
        }
        return listDataToMapping;
    }
    public static List<List<Integer>> changeDataTrainToNumber(List<String> data, Map<String, Integer> mappingValue){
        List<List<Integer>> listData = new ArrayList<>();
        for (String s : data){
            String[] temp = s.split(", ");
            List<Integer> dataAdd = new ArrayList<>();
            for (String s2 : temp){
                dataAdd.add(mappingValue.get(s2));
            }
            listData.add(dataAdd);
        }
        return listData;
    }
    public static void reverseDataMapping(Map<String, Integer> data){
        reverseMapping = new HashMap<>();
        for (Map.Entry<String, Integer> entry : data.entrySet()){
            reverseMapping.put(entry.getValue(), entry.getKey());
        }
    }
    public static List<Integer> changeInputFoodToNum(List<String> data){
        List<Integer> dataPrepared = new ArrayList<>();
        for (String s : data){
            dataPrepared.add(dataMapping.get(s));
        }
        return dataPrepared;
    }
    public List<String> makeList (){
        return Arrays.asList("Bầu Xào",
                "Bò Bít Tết",
                "Cá Hú",
                "Thịt bò xào đỗ trạch",
                "Thịt bò xào sả ớt",
                "Thịt Heo Kho Trứng Cút",
                "Cá hồi lúc lắc",
                "Bò cuộn xúc xích chiên giòn",
                "Canh Mướp Mồng Tơi",
                "Canh Mồng Tơi Nấu Thịt Heo",
                "Bắp Cải Luộc",
                "Canh bí xanh hầm xương",
                "Ổi",
                "Chả lá lốt",
                "Gỏi củ hủ dừa",
                "Salad trứng",
                "Cải Thìa Xào",
                "Canh Rau Má",
                "Chả Mực Chiên",
                "Bao tử cá basa xào hành tây",
                "Miến Trộn Chay",
                "Canh Rong Biển Nấu Thịt Bò",
                "Canh Súp Lơ Xanh Nấu Thịt Heo",
                "Mề gà xào cay",
                "Bánh Canh Cua",
                "Nộm su hào cà rốt",
                "Thịt rán",
                "Giá Hẹ Xào Thịt Gà",
                "Nấm Rơm Xào Đậu Hủ",
                "Canh xương hầm khoai",
                "Nem thính tai cuộn lá sung",
                "Vịt Kho Gừng",
                "Gà chiên nước mắm",
                "Bún Gạo Xào Thập Cẩm",
                "Gà Chiên Nước Mắm",
                "Rau Củ Xào Thập Cẩm",
                "Canh sườn bò Hàn Quốc",
                "Canh Đu Đủ Xanh Nấu Tôm",
                "Canh Khổ Qua Nấm",
                "Canh Rau Ngót Thịt Heo",
                "Canh Bí Đao Nấu Tôm",
                "Bún Thịt Bò Xào",
                "Canh cua mướp hương",
                "Súp lơ xào cà rốt",
                "Bánh mì ốp la",
                "Cá Thu Chiên Sốt Cà",
                "Sung muối",
                "Canh ngao nấu bầu",
                "Mực Xào Thập Cẩm",
                "Mận",
                "Dưa chuột ngâm chua ngọt",
                "Canh Bí Xanh",
                "Súp Lơ Xanh Cà Rốt Xào",
                "Giá Mướp Xào Tôm Khô",
                "Mướp Xào",
                "Nui Xào Chay",
                "Bánh Cuốn",
                "Thịt bò xào thập cẩm",
                "Sữa Pha Sẵn Growplus",
                "Tôm chiên xù",
                "Bông Hẹ Xào Thịt Bò",
                "Canh cà chua trứng",
                "Khoai Lang",
                "Cần Tây Xào Gan Heo",
                "Nuvi Sữa Lắc Trái Cây",
                "Canh Kim Chi",
                "Súp Lơ Xanh Cà Rốt Xào Thịt Bò",
                "Chả Cua Hấp",
                "Chân giò hầm hạt sen",
                "Cá thu rim mắm tỏi",
                "Thịt viên sốt nấm",
                "Sườn Nấu Đậu",
                "Chả Chay Kho Tiêu",
                "Cá nục kho mía",
                "Tôm Chiên Giòn",
                "Lựu nữ hoàng",
                "Ức Gà Kho Sả",
                "Sinh tố xoài",
                "Cà Bát Xào Thịt Heo",
                "Súp cua",
                "Sữa tươi",
                "Blendy gạo rang kem chuối",
                "Chôm Chôm Thái",
                "Đu Đủ Chín (80g/phần - 1/8 Trái Vừa)",
                "Tôm rim mặn,Mít",
                "Đào",
                "Chè nhãn nhục",
                "Gan lợn xào",
                "Canh su hào thịt bằm",
                "Canh cải xoong tôm tươi",
                "Táo Tây",
                "Miến Trộn Rau Củ Chay",
                "Lẩu cá thác lác",
                "Cải Thìa Xào Tỏi",
                "Tôm băm rim",
                "Rau cải luộc",
                "Canh Khổ Qua Nấu Cá Thác Lác",
                "Vịt kho riềng ớt khô",
                "Canh Bí Đỏ Nấu Thịt Heo",
                "Thịt bò xào ớt chuông",
                "Nấm Xào Sả Ớt",
                "Canh Cà Rốt Khoai Tây Nấu Thịt Bằm",
                "Vú Sữa",
                "Nutimilk Sữa Tươi 100 Điểm Ít Đường Hộp 180ml",
                "Tôm hấp nước dừa",
                "Gà Kho Hành Gừng",
                "Xu hào xào",
                "Gà quay",
                "Mực Xào Chua Ngọt",
                "Sườn kho khoai tây",
                "Cá Nục Chiên",
                "Xoài",
                "Trứng Chiên Nấm",
                "Chè đậu xanh nha đam",
                "Mực chiên mắm tỏi",
                "Thịt Heo Sốt Chua Ngọt",
                "Canh tôm bồ ngót",
                "Chân giò hầm",
                "Cá Chim Chiên",
                "Đậu phụ chiên ròn",
                "Cà muối chua",
                "Đậu Đũa Xào Thịt Heo",
                "Cốt Lết Ram Mè",
                "Cá Chim Kho Ngót",
                "Khoai Tây Xào Thịt Bò",
                "Cà muối",
                "Canh bò nấu dưa chua",
                "Đu Đủ Chín",
                "Salad",
                "Bò Hầm Tiêu Xanh",
                "Su hào ngâm chua ngọt",
                "Canh Đu Đủ Xanh Nấu Thịt Heo",
                "Thạch chanh leo",
                "Súp Lơ Xanh Luộc",
                "Canh xương hầm măng khô",
                "Củ năng om nấm chay",
                "Thịt kho hột vịt",
                "Dưa Leo",
                "Canh Bí Đỏ Nấu Tôm",
                "Gỏi tôm mực kiểu Thái",
                "Lựu",
                "Cá Hồi Chiên",
                "Chả giò hải sản",
                "Rau lang xào",
                "Bánh Mì Thịt Nướng",
                "Nem tôm rán giòn rụm",
                "Quả Bơ Vỏ Xanh",
                "Đậu thịt sốt cà chua",
                "Cánh Gà Chiên Giòn",
                "Súp Lơ Xào Mực",
                "Nấm Sốt Dầu Hào",
                "Đậu nhồi thịt sốt cà chua",
                "Dưa chuột cắt lát",
                "Khổ Qua (Mướp Đắng) Xào Trứng",
                "Bún bò huế",
                "Tôm rang mặn ngọt",
                "Xíu Mại Kho Cà",
                "Cá chép chiên giòn cuốn bánh tráng",
                "Cánh gà nướng sốt BBQ",
                "Thịt chưng mắm tép",
                "Sườn Non Xào Chua Ngọt",
                "Dưa Bở",
                "Phi Lê Cá Basa Chiên",
                "Bò kho gừng sả",
                "Cải ngọt xào tôm",
                "Nem rán giòn",
                "Tàu Hủ Ky Xào Rau Củ",
                "Đậu Cô Ve (Đậu Que) Xào Thịt Bò",
                "Su hào xào trứng",
                "Đậu Rồng Luộc",
                "Viên xúc xích trứng cút chiên",
                "Cá Diêu Hồng Kho Hành Gừng",
                "Canh Khoai Mỡ Nấu Thịt Heo",
                "Trứng cút sốt chua ngọt",
                "Tôm Sốt Cà",
                "Canh Cải Cúc Nấu Thịt Heo",
                "Nước Cam Tươi",
                "Nho Ngọt",
                "Củ cải luộc",
                "Nấm xào",
                "Bò xào đậu que",
                "Canh sương hầm củ quả",
                "Gỏi bắp bò",
                "Đậu Hũ Sốt Cà",
                "Dưa muối chua ăn kèm thịt cân giò",
                "Sườn Cốt Lếch Ram",
                "Bầu Xào Thịt Bằm",
                "Bánh mì",
                "Canh Cải Bó Xôi Thịt Bò",
                "Thịt bê xào lăn",
                "Chả giò tôm cua",
                "Súp Lơ Xanh Xào Tôm",
                "Canh Khoai Củ Thịt Bằm",
                "Canh Cải Cúc Nấu Cá Thác Lác",
                "Canh rau cải",
                "Canh Bầu Nấu Tôm",
                "Mực Nhồi Thịt Hấp",
                "Xu hào ngâm chua ngọt",
                "Thịt gà luộc",
                "Canh xương bí xanh",
                "Tôm Xào Thập Cẩm",
                "Mực né",
                "Cá Nục Kho",
                "Cá bống trứng kho tiêu",
                "Bí đỏ xào tràng trứng",
                "Mực xào đậu Hà Lan",
                "Tôm Rim Thịt Ba Rọi",
                "Xíu Mại Nhồi Trứng Cút",
                "Bắp Nếp Luộc",
                "Nem lụi",
                "Đậu Cove Luộc",
                "Ếch Xào Lăn",
                "Nutimilk Sữa Chua Có Đường Hộp 100g",
                "Gà Nướng Mật Ong",
                "Canh Chua Cá Thát Lát",
                "Sườn nướng BBQ",
                "Cá hấp mồng tơi",
                "Gà Hấp Lá Chanh",
                "Canh xương hầm củ quả",
                "Súp Tôm",
                "Cá thu sốt cà chua",
                "Bò Xào Dưa Chua",
                "Cá Bống Chiên Giòn",
                "Canh Cải Bó Xôi Thịt Heo",
                "Quả Thanh Long",
                "Mì Ý Sốt Bò Bằm",
                "Canh Bắp Cải Nấu Tôm",
                "Súp mộc nhĩ thịt cua",
                "Bí đỏ xào tỏi",
                "Mít Non Xào",
                "Dưa góp su hào cà rốt",
                "Sườn Nướng Chay",
                "Rau câu",
                "Trứng Gà Chiên Thịt Bằm",
                "Quýt Đường",
                "Cuốn chay đậu hũ rau rừng",
                "Cá chim chiên giòn",
                "Salad Trộn Giấm",
                "Canh Khoai Tây Cà Rốt Nấm Hương",
                "Chuối Cau",
                "Canh Bầu",
                "Cá Hú Kho Tiêu",
                "Cá thu sốt xì dầu",
                "Cá chép kho riềng",
                "Miến Sườn Heo",
                "Đậu phụ rán",
                "Dưa Leo Cà Chua Xà Lách",
                "Thịt chân giò luộc",
                "Dưa Hấu",
                "Đậu Cove",
                "Nutimilk Sữa Tươi 100 Điểm Có Đường Hộp 110ml",
                "Salad bít tết",
                "Sườn non ram kho mặn ngọt",
                "Măng Xào Đậu Hũ",
                "Thịt ba chỉ luộc",
                "Canh ngao nấu chua",
                "Măng Cụt",
                "Cá điêu hồng hấp xì dầu",
                "Rau Muống Luộc",
                "Giá Đỗ Xào",
                "Lẩu thập cẩm",
                "Nuvi Sữa Lắc Trái Cây Hương Trái Cây Nhiệt Đới",
                "Canh Đu Đủ Xanh",
                "Cuống họng lợn luộc",
                "Gỏi ngó sen tôm thịt",
                "Rau câu dừa",
                "Susu Xào",
                "Bò sốt tiêu đen",
                "Na",
                "Dưa Lê",
                "Nho",
                "Canh Cà Rốt Khoai Tây Thịt Bằm",
                "Su Su Xào Tỏi",
                "Salad dưa chuột",
                "Trứng chiên thịt bằm",
                "Thịt viên chiên",
                "Bún Khô Trộn Ức Gà",
                "Mì Xào Chay",
                "Lẩu kim chi phô mai",
                "Cá Trê Chiên Mắm Gừng",
                "Canh Cải Thảo",
                "Thịt nướng sốt BBQ",
                "Canh ốc mồng tơi",
                "Thịt nướng xá xíu",
                "Lạc rang muối",
                "Cá basa fillet chiên trứng",
                "Chả cốm chiên vàng",
                "Củ Sắn",
                "Đậu phụ tẩm hành",
                "Rau Củ Xào Tôm",
                "Salad cá hồi sốt tôm khô",
                "Mướp Xào Lòng Gà",
                "Cải Ngọt Luộc",
                "Bún Chả",
                "Bò Nấu Đậu",
                "Thịt Heo Nạc Chiên Sả",
                "Hồng Xiêm",
                "Bò Xào Hành",
                "Nui Sườn Heo",
                "Bánh Canh Tôm Thịt",
                "Gỏi Măng Tươi",
                "Nước Dừa Tươi Non",
                "Canh Cải Soong Nấu Thịt Bò",
                "Mì Ý bò băm",
                "Súp Lơ Cà Rốt Luộc",
                "Cá chim sốt cà chua",
                "Chuối Tiêu",
                "Móng giò luộc",
                "Thịt kho trứng cút",
                "Sườn rim chua ngọt",
                "Bông Cải Cà Rốt Xào",
                "Lê",
                "Sườn nướng",
                "Ếch Chiên Nước Mắm",
                "Giá Hẹ Xào",
                "Súp Lơ Xanh Xào",
                "Canh Cải Thảo Nấu Thịt Heo",
                "Súp Lơ Xanh Xào Cà Rốt",
                "Gà luộc",
                "Ngồng cải luộc",
                "Cánh gà chiên nước mắm",
                "Canh bí nấu mọc",
                "Canh Đu Đủ",
                "Rau bí xào tỏi",
                "Canh bí đỏ",
                "Canh đậu thịt viên",
                "Bánh Bao Nhân Thịt",
                "Tôm rim",
                "Chuối Già",
                "Canh Mướp Mồng Tơi Nấu Tôm",
                "Canh ghẹ rau muống",
                "Canh mồng tơi thịt băm",
                "Nước Cam Vắt Nguyên Chất",
                "Chè khúc bạch",
                "Bánh Mì Trứng Ốp La",
                "Canh Bí Đao Nấu Thịt Heo",
                "Canh Bông Cải Nấm Rơm Thịt Heo",
                "Quít",
                "Canh chua cá khoai",
                "Sườn Nướng Mật Ong",
                "Canh Cải Soong Nấu Thịt Heo",
                "Bánh Canh Giò Heo",
                "Mướp luộc",
                "Cháo Thập Cẩm",
                "Hồng xiêm",
                "Chôm Chôm",
                "Tôm Rim",
                "Chả giò rong biển chay",
                "Cơm giòn tôm kho quẹt",
                "Canh Mồng Tơi Nấu Tôm",
                "Gà Kho Nấm Hương",
                "Rau Muống Xào Tỏi",
                "Cà tím nhồi thịt nướng",
                "Cơm Trắng Gạo Tài Nguyên",
                "Thịt xào hành",
                "Chôm Chôm Nhãn",
                "Cá kho tộ",
                "Cơm",
                "Bánh crepe áp chảo",
                "Pizza khoai tây",
                "Chả Cá Kho Thơm",
                "Mướp xào lòng gà",
                "Bánh Mì Ngũ Cốc Lúa Mạch Đen",
                "Đậu Hũ Kho Nấm Rơm",
                "Rau củ luộc",
                "Canh chua cá",
                "Cá chép rán giòn",
                "Canh rau cải thịt băm",
                "Canh Bắp Cải Cà Rốt",
                "Khổ Qua (Mướp Đắng) Xào",
                "Cà Chua Dồn Thịt Chay",
                "Canh Bắp Cải Nấu Thịt Heo",
                "Đậu hũ nhồi thịt sốt cà chua",
                "Cá Hú/ Cá Basa Kho Cà",
                "Đậu Bắp Luộc",
                "Chả Cá Thu Chiên",
                "Canh mướp thịt băm",
                "Đậu Hủ Chiên Sả",
                "Canh Cải Bó Xôi Nấu Tôm",
                "Củ cải xào",
                "Chân giò luộc",
                "Bắp Cải Xào Thịt Heo",
                "Đậu Hũ Dồn Thịt Sốt Cà",
                "Thịt nướng",
                "Thanh long",
                "Mực chiên mắm",
                "Sữa Đậu Nành Bổ Sung Canxi Nuti",
                "Sữa Đậu Nành Bổ Sung Canxi Nuti Bịch 200ml",
                "Cải Thìa Xào Nấm Hương",
                "Cá Ngừ Kho Thơm",
                "Cải Thìa Xào Thịt Heo",
                "Cá Lóc Kho Tộ",
                "Nuvi Sữa Chua Uống Men Sống Chai 65ml",
                "Sườn xào chua ngọt",
                "Thịt bò xào củ niễng",
                "Đậu xanh (đỗ) luộc",
                "Cá thu rim dầu hào",
                "Váng đậu cuộn thịt chiên giòn",
                "Thịt bò xào cần tây",
                "Cải Thìa Sốt Nấm Đông Cô",
                "Cá thu chiên",
                "Canh gân bò nấu dưa chua",
                "Chả Cá Thát Lát Chiên",
                "Mận Hà Nội",
                "Cá Thu Kho Cà",
                "Trứng chiên thịt",
                "Canh Cải Cúc Nấu Tôm",
                "Rau muống luộc",
                "Cá lanh kho khô",
                "Súp lơ cà rốt luộc",
                "Salad rong nho xốt mè rang",
                "Rau muống xào tỏi",
                "Canh Cải Xanh",
                "Đậu Hủ Chiên Chấm Tương",
                "Đậu quả xào tỏi",
                "Canh Chua Rau Muống Nấu Tôm",
                "Đậu Hũ Kho Thịt",
                "Nuvi Sữa Lắc Trái Cây Hương Cam Cho Trẻ 1 Tuổi Trở Lên Hộp 110ml",
                "Hủ Tíu Bò Kho Chay",
                "Nutimilk Sữa Tươi",
                "Salad cá ngừ",
                "Khoai môn lệ phố",
                "Cá rô phi tẩm bột chiên",
                "Cơm Trắng Gạo Thường",
                "Súp lơ xào",
                "Canh Rong Biển Nấu Tôm",
                "Tôm Sốt Nấm",
                "Gỏi gà cần tây",
                "Canh Khoai Mỡ",
                "Canh khoai sọ hầm xương",
                "Đậu Hũ Thịt Bằm Sốt Cà Chua",
                "Canh sườn nấu chua",
                "Canh cải cúc thịt băm",
                "Blendy trà đào cam sả",
                "Canh Su Su Cà Rốt",
                "Giá Mướp Xào Thịt Heo",
                "Mướp Xào Gan Gà",
                "Canh ngao mồng tơi",
                "Táo",
                "Mì Quảng",
                "Xoài tráng miệng",
                "Canh cua rau đay",
                "Xoài Chín",
                "Cá kho thịt",
                "Bắp Cải Xào",
                "Thịt ba rọi rang cháy cạnh",
                "Canh Đu Đủ Xanh Nấu Sườn Heo",
                "Canh Bầu Nấu Thịt Bằm",
                "Cà Ry Đậu Hũ Chay",
                "Trứng cút luộc",
                "Cá quả kho tộ",
                "Xúc xích dưa cải",
                "Thịt bò xào đỗ",
                "Thịt Heo Kho Củ Cải",
                "Canh rau ngót",
                "Bí Đao Đậu Bắp Luộc",
                "Cà Tím Xào Thịt Bằm",
                "Cá trắm kho giềng",
                "Đậu phụ chiên",
                "Salad bơ bacon",
                "Trứng cuộn rau củ",
                "Nấm xào thập cẩm",
                "Chả đậu phụ",
                "Vịt om sấu khoai sọ",
                "Canh bí xanh nấu thịt",
                "Đậu Hủ Kho Rau Củ Chay",
                "Gà Kho Sả",
                "Súp gà mọc nấm hương",
                "Rau Muống Xào Thịt Bò",
                "Canh sườn đậu phộng xá bấu",
                "Gà hấp tứ quý chay",
                "Thịt đông",
                "Salad Dưa Leo",
                "Nghêu kho nước tương",
                "Đậu Que Xào Cà Rốt",
                "Thịt viên sốt cà chua",
                "Xoài chín",
                "Thịt Ba Rọi Kho Mắm Ruôc",
                "Chả Giò Chay",
                "Canh Cải Xanh Nấu Cá Thác Lác",
                "Salad rau củ",
                "Canh cá",
                "Bò Lúc Lắc",
                "Lòng lợn luộc",
                "Thịt Heo Nạc Kho Tiêu",
                "Cam Vàng",
                "Canh Khổ Qua Nhồi Thịt",
                "bưởi",
                "Phi Lê Cá Điêu Hồng Chiên",
                "Nước Ép Cà Rốt 100%",
                "Canh Củ Sen Nấu Nấm Mỡ",
                "Canh Rau Dền Nấu Thịt Heo",
                "Gà Rô Ti",
                "Súp gà nấm",
                "Bắp giò luộc",
                "Bông bí xào tỏi",
                "Canh chua cá lóc đậu tương",
                "Nhãn",
                "Ngọn Su Su Xào Thịt Bò",
                "Cải Thìa Sốt Dầu Hào",
                "Giò thủ",
                "Đậu phụ chiên vàng",
                "Thịt viên nấm sốt cà chua",
                "Mì Căn Xào Sả",
                "Cải Ngọt Xào Tỏi",
                "Xoài Sống",
                "Canh cà chua",
                "Su Su Cà Rốt Xào Tôm",
                "Cá nục kho tóp mỡ",
                "Đậu Hà Lan Xào Tỏi",
                "Dưa muối",
                "Trứng cút chiên sả ớt",
                "Bún Mọc",
                "Mãng Cầu Ta",
                "Táo Ta",
                "Rau mồng tơi luộc",
                "Đậu phụ sốt mắm hành",
                "Bánh Mì Sanwich Thịt Nguội",
                "Canh Rau Ngót",
                "Cá Cơm/ Cá Bống Kho Tiêu",
                "Cà pháo mắm tôm",
                "Sườn chay om nấm đùi gà",
                "Thịt băm rau củ",
                "Canh bí nấu nước dùng gà",
                "Nấm Rơm Xào Lòng Gà",
                "Mì trộn sốt kho quẹt",
                "Cá bạc má kho",
                "Thịt kho tàu",
                "Bún Bò Huế",
                "Canh rau muống",
                "Bún Riêu Chay",
                "Trứng Cuộn Tam Sắc",
                "Chuối",
                "Cam",
                "Cà pháo muối chua",
                "Canh Măng Chua Cá Điêu Hồng",
                "Bưởi",
                "Bầu Đậu Bắp Luộc",
                "Thịt Heo Nhồi Cà Chua",
                "Dưa cải củ muối",
                "Cải Chua Xào Thịt Heo",
                "Cá thu sốt tỏi",
                "Canh Bí Đỏ",
                "Đậu Hủ Non Thịt Bằm Sốt Cà Chua",
                "Bao tử cá basa xào",
                "Bò né bông điên điển",
                "Canh Cải Cúc Đậu Hũ",
                "Thịt bò xào ớt chuông cần tỏi",
                "Đu đủ",
                "Canh sấu thịt băm",
                "Bò xào cần tỏi",
                "Miến Thịt Gà Nấu Nấm",
                "Măng Xào Mực Tươi",
                "Sữa Chua Trộn Trái Cây",
                "Đùi ếch chiên",
                "Thịt nạc kho tiêu",
                "Canh bóng thập cẩm",
                "Bánh flan",
                "Bì nấu đông",
                "Miến Lươn",
                "Cơm sen gạo lứt chay",
                "Canh cải ngọt thịt băm",
                "Cải mèo xào thịt bò",
                "Dưa Lưới",
                "Khoai Mì Chấm Muối Mè",
                "Súp lươn",
                "Ngao hấp thái",
                "Cá hồi hạnh nhân xốt chanh dây",
                "Bò Xào Hành Cần",
                "Tôm sú nướng muối ớt",
                "Canh Rau Ngót Nấu Thịt Bằm",
                "Canh Chua Nấm Kim Châm",
                "Susu Cà Rốt Xào Chay",
                "Đậu quả xào",
                "Sữa Tươi Tiệt Trùng Th True Milk",
                "Da heo chiên nước mắm",
                "Panna Cotta kem muối",
                "Mực Nhồi Thịt Chiên",
                "Sườn rim nước dừa",
                "Cá bạc má chiên",
                "Miến xào cua",
                "Su su xào tỏi",
                "Canh rau ngót thịt băm",
                "Canh Bí Đỏ Đậu Phộng",
                "Canh Rau Đay Nấu Cua",
                "Đậu Hủ Kho Dưa Cải",
                "Lẩu sườn khoai môn",
                "Canh Súp Lơ Cà Rốt",
                "Canh Cà Chua Trứng Gà",
                "Rau cải xào",
                "Canh Rau Dền",
                "Su Su Cà Rốt Xào");
    }

    @PostConstruct
    public void init() throws InterruptedException {
        List<String> data = makeList();
        foodService.addData(data);
        System.out.println("Đã thực hiện thành công !");
        prepareData();
    }
}
